### PR TITLE
Fix events catching on rotated ellipse annotations

### LINKED ISSUE #580: Rotated ellipse annotation does not catch the events
When an ellipse annotation is rotated, it doesn't catch the events.

This happens because in `inRange` method, the rotation is ignored.

Codepen: https://codepen.io/stockinail/pen/ExwXjEe

The sample is rotated of 90 degrees and if you click out of ellipse (original size with rotation 0), the events is caught even if is outside of the annotation.

### PR DESCRIPTION
**Pull request by stockiNail**
Fix #580

### CODE REVIEW

**Comment by stockiNail** [comment]
@kurkle as usual, I write step by step about math calculations... For sure, you don't like it ;)

**Comment by stockiNail** [comment]
@kurkle I didn't set the milestone because I don't know if you want to release it in 1.3.0 or before with another release

File: src/types/ellipse.js [hunk 1]
```diff
@@ -77,6 +77,11 @@ function pointInEllipse(p, ellipse) {
...
   }
-
-  return (Math.pow(p.x - center.x, 2) / Math.pow(xRadius, 2)) + (Math.pow(p.y - center.y, 2) / Math.pow(yRadius, 2)) <= 1.0;
+  // https://stackoverflow.com/questions/7946187/point-and-ellipse-rotated-position-test-algorithm
+  const angle = toRadians(rotation || 0);
+  const cosAngle = Math.cos(angle);
+  const sinAngle = Math.sin(angle);
+  const a = Math.pow(cosAngle * (p.x - center.x) + sinAngle * (p.y - center.y), 2);
+  const b = Math.pow(sinAngle * (p.x - center.x) - cosAngle * (p.y - center.y), 2);
+  return (a / Math.pow(xRadius, 2)) + (b / Math.pow(yRadius, 2)) <= 1;
```
Comment (kurkle) [inline src/types/ellipse.js:86]: Do the width and height need to be adjusted?

Comment (stockiNail) [reply src/types/ellipse.js:86]: No, they don't. At least I don't think so. Why?

Comment (kurkle) [reply src/types/ellipse.js:86]: I was thinking it should be the rotated xRadius/yRadius that we need to compare against, but is it?

I think this one would deserve some dedicated tests.

Comment (stockiNail) [reply src/types/ellipse.js:86]: in my opinion, width and height should be affected by a rotation, because they are remaining the same. But I could be wrong.
In fact, in the stackoverflow, where I took the solution, the width and height are not touched by rotation.

Comment (stockiNail) [reply src/types/ellipse.js:86]: > I think this one would deserve some dedicated tests.

added specific test case on rotated ellipse

**Review by kurkle — APPROVED** [review]
